#!/usr/bin/env python3
"""Generate report evidence and enforce review fingerprints (Python standard library)."""
import argparse
import csv
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import statistics
import sys

ROOT = Path(__file__).resolve().parents[1]
REPORT = Path('docs/report')
LOCK = REPORT / 'source-lock.json'
OUTPUT = REPORT / 'data.js'


def snapshot(root):
    """Detect edits, additions and removals; never fingerprint generated outputs."""
    paths = {root / p for p in ['CMakeLists.txt', 'AGENTS.md', 'README.md', 'CLAUDE.md', '.github/workflows/ci.yml']}
    for folder in ['src', 'include', 'tests', 'tools', 'docs']:
        paths.update(p for p in (root / folder).rglob('*')
                     if p.is_file() and '__pycache__' not in p.parts
                     and p.suffix in {'.cpp', '.hpp', '.py', '.md', '.csv', '.txt', '.html', '.css', '.js', '.json'})
    return {str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(paths) if p.is_file() and p.relative_to(root) not in {LOCK, OUTPUT}}


def summary(path):
    with path.open() as source:
        rows = list(csv.DictReader(source))
    if not rows:
        raise ValueError(f'Empty benchmark: {path}')
    results = []
    for engine in ('hybrid', 'greedy'):
        samples = [r for r in rows if r['engine'] == engine]
        if not samples:
            raise ValueError(f'Missing engine {engine}: {path}')
        cases = {}
        for row in samples:
            key = (row['start_node'], row['seed'])
            stable = {k: v for k, v in row.items() if k not in ('repeat', 'wall_ms')}
            if key in cases and stable != cases[key]:
                raise ValueError(f'Non-deterministic case: {path}, {key}')
            cases[key] = stable
        valid = [r for r in cases.values() if r['valid'] == '1']
        times = sorted(float(r['wall_ms']) for r in samples)
        results.append(dict(engine=engine, cases=len(cases), valid=len(valid),
                            in_tolerance=sum(r['within_tolerance'] == '1' for r in cases.values()),
                            mean_fitness=statistics.mean(float(r['fitness']) for r in valid) if valid else 0,
                            mean_error_m=statistics.mean(float(r['error_m']) for r in valid) if valid else 0,
                            median_ms=statistics.median(times), p90_ms=times[int(.9 * (len(times)-1))],
                            samples=len(times)))
    return results


def render(root, lock):
    archived = root / 'docs/benchmarks/2026-09-29'
    source = (root / 'src/main.cpp').read_text()
    cli_help = re.findall(r'"  (--[^"\n]+)\\n"', source)
    data = dict(review={k: lock[k] for k in ('date', 'note', 'source_digest')},
                cli_help=cli_help,
                benchmarks=dict(curated=summary(archived/'precheck.csv'), heldout=summary(archived/'heldout.csv')),
                routes={name: json.loads((root/REPORT/'fixtures'/filename).read_text()) for name, filename in
                        [('point', 'example-route.json'), ('area', 'area-route.json')]})
    # Data is executable only as an assignment; escape markup boundaries defensively.
    return '/* Generated by tools/build_report.py; do not edit. */\nwindow.VELOGRAPH_REPORT = ' + json.dumps(data, indent=2, ensure_ascii=True).replace('<', '\\u003c') + ';\n'


def refresh(root, note):
    files = snapshot(root)
    digest = hashlib.sha256(json.dumps(files, sort_keys=True).encode()).hexdigest()
    lock = dict(date=datetime.now(timezone.utc).date().isoformat(), note=note, source_digest=digest, files=files)
    content = render(root, lock)  # Validate inputs before changing either generated artifact.
    (root/LOCK).write_text(json.dumps(lock, indent=2, sort_keys=True)+'\n')
    (root/OUTPUT).write_text(content)


def check(root):
    lock = json.loads((root/LOCK).read_text())
    current = snapshot(root)
    changed = sorted(p for p in current.keys() | lock['files'].keys() if current.get(p) != lock['files'].get(p))
    if changed:
        raise ValueError('Report review is stale for:\n  ' + '\n  '.join(changed) +
                         '\nReview affected explanations/evidence, then --refresh --note "...".')
    digest = hashlib.sha256(json.dumps(current, sort_keys=True).encode()).hexdigest()
    if lock['source_digest'] != digest:
        raise ValueError('Manifest fingerprint mismatch')
    if (root/OUTPUT).read_text() != render(root, lock):
        raise ValueError('Generated report evidence is stale or edited; regenerate after review.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--refresh', action='store_true')
    parser.add_argument('--note', help='What changed and which explanations/evidence were reviewed')
    args = parser.parse_args()
    if args.refresh:
        if not args.note or len(args.note.strip()) < 15:
            parser.error('--refresh requires a meaningful --note (at least 15 characters)')
        refresh(ROOT, args.note)
    else:
        check(ROOT)
    print('Report review and generated evidence are current.')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, KeyError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
